spring.datasource.url=jdbc:postgresql://localhost:5432/sam
spring.datasource.username=postgres
spring.datasource.password=vjg'dv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

server.port=8080